public class Tester{
  public static void main(String[] args) {
    RealNumber r1 = new RealNumber(43);
    RealNumber r2 = new RealNumber(34);
    RealNumber r3 = new RealNumber(-2.2);
    RealNumber r4 = new RealNumber(1.42);
    RealNumber r5 = new RealNumber(0.0);
    RealNumber r6 = new RealNumber(-2.2);
    System.out.println("TEST CASES FOR REAL NUMBER:");
    System.out.println(r1.getValue());
    System.out.println(r1.add(r2));
    System.out.println(r1.multiply(r2));
    System.out.println(r1.subtract(r2));
    System.out.println(r1.divide(r2));
    System.out.println(r1.getValue());
    System.out.println(r1);
    System.out.println("---------------------");
    System.out.println(r3.getValue());
    System.out.println(r3.add(r6));
    System.out.println(r3.multiply(r6));
    System.out.println(r3.subtract(r6));
    System.out.println(r3.divide(r6));
    System.out.println(r3.getValue());
    System.out.println(r3);
    System.out.println("---------------------");
    System.out.println(r4.getValue());
    System.out.println(r4.add(r3));
    System.out.println(r4.multiply(r3));
    System.out.println(r4.subtract(r3));
    System.out.println(r4.divide(r3));
    System.out.println(r4.getValue());
    System.out.println(r4);
    System.out.println("---------------------");
    System.out.println();
    System.out.println("TEST CASES FOR RATIONAL NUMBER:");
    RationalNumber t1 = new RationalNumber(8,6);
    RationalNumber t2 = new RationalNumber(16, 12);
    RationalNumber t3 = new RationalNumber(1, 0);
    RationalNumber t4 = new RationalNumber(32, -3);
    RationalNumber t5 = new RationalNumber(4, 7);
    RationalNumber t6 = new RationalNumber(13, -9);
    System.out.println(t3.getValue());
    System.out.println(t4.getValue());
    System.out.println(t3.getNumerator());
    System.out.println(t4.getNumerator());
    System.out.println(t3.getDenominator());
    System.out.println(t4.getDenominator());
    System.out.println(t3.reciprocal());
    System.out.println(t4.reciprocal());
    System.out.println(t3.equals(t4));
    System.out.println(t3.multiply(t4));
    System.out.println(t3.divide(t4));
    System.out.println(t3.add(t4));
    System.out.println(t3.subtract(t4));
    System.out.println(t3.compareTo(t4));
    System.out.println("---------------------");
    System.out.println(t1.getValue());
    System.out.println(t2.getValue());
    System.out.println(t1.getNumerator());
    System.out.println(t2.getNumerator());
    System.out.println(t1.getDenominator());
    System.out.println(t2.getDenominator());
    System.out.println(t1.reciprocal());
    System.out.println(t2.reciprocal());
    System.out.println(t1.equals(t2));
    System.out.println(t1.multiply(t2));
    System.out.println(t1.divide(t2));
    System.out.println(t1.add(t2));
    System.out.println(t1.subtract(t2));
    System.out.println(t1.compareTo(t2));
    System.out.println("---------------------");
    System.out.println(t5.getValue());
    System.out.println(t6.getValue());
    System.out.println(t5.getNumerator());
    System.out.println(t6.getNumerator());
    System.out.println(t5.getDenominator());
    System.out.println(t6.getDenominator());
    System.out.println(t5.reciprocal());
    System.out.println(t6.reciprocal());
    System.out.println(t5.equals(t6));
    System.out.println(t5.multiply(t6));
    System.out.println(t5.divide(t6));
    System.out.println(t5.add(t6));
    System.out.println(t5.subtract(t6));
    System.out.println(t5.compareTo(t6));
  }
}
